version: "3.9"

name: "key-generator"

services:
  db:
    restart: always
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    ports:
      - "5656:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume:
